config/routes.rb
Rails.application.routes.draw do
  root to: 'home#top'
  get 'home/about', to: 'home#about', as: 'about'
  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  devise_for :users
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  #titleとopinionが入力されているか確認
  validates :title, presence: true
  validates :body, presence: true
  validates :body, length: { in: 1..200 }
  
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates_uniqueness_of :book_id, scope: :user_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_one_attached :profile_image
  
  validates :name, length: { in: 2..20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/default-image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top,:about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = book.id
    comment.save
    redirect_back(fallback_location: root_path)
  end
  
  def destroy
    BookComment.find(params[:id]).destroy
    redirect_back(fallback_location: root_path)
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :correct_user, only: [:edit, :update]
  
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully." 
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      @user = current_user
      render :index
    end
  end

  def index
    @book = Book.new
    @books = Book.all
    @user = current_user
  end

  def show
    @book = Book.find(params[:id])
    @book_user = User.find(@book.user_id)
    @user = current_user
    @book_comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  # 投稿データのストロングパラメータ
  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
  
  def correct_user
    @book = Book.find(params[:id])
    @user = @book.user
    redirect_to(books_path) unless @user == current_user
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_back(fallback_location: root_path)
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user, only: [:edit, :update]
  
  def show
    @user = User.find(params[:id])
    @books = @user.books
  end

  def index
    @user = current_user
    @users = User.all
  end

  def edit
    @user = current_user
  end
  
  def update
    @user = current_user
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end
  
  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
  
  def correct_user
    @user = User.find(params[:id])
    redirect_to(user_path(current_user)) unless @user == current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_books_list.html.erb
<h2>Books</h2>
<table class="table">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td>
          <%= link_to user_path(book.user_id) do %>
            <%= image_tag book.user.get_profile_image(80,80) %>
          <% end %>
        </td>
        <td>
          <%= link_to book.title, book_path(book.id) %>
        </td>
        <td>
          <%= book.body %>
        </td>
        <td>
          <% if book.favorited_by?(current_user) %>
            <p>
              <%= link_to book_favorites_path(book), method: :delete do %>
                <i class="fa-solid fa-heart text-danger">
                  <%= book.favorites.count %>
                </i>
              <% end %>
            </p>
            <% else %>
            <p>
              <%= link_to book_favorites_path(book), method: :post do %>
                <i class="fa-regular fa-heart">
                  <%= book.favorites.count %>
                </i>
              <% end %>
            </p>
          <% end %>
        </td>
        <td>
          <p>コメント数：<%= book.book_comments.count %></p>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/_new.html.erb
<h2 class="mt-3">New book</h2>
<%= form_with model: Book do |f| %>
  <div class="form-group">
    <%= f.label :title, 'Title' %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :body, 'Opinion' %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class="form-group">
    <%= f.submit 'Create Book', class: 'btn btn-success btn-sm'%>
  </div>
<% end %>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
      <%= render 'shaerd/error_explanation', valid: @book%>
      <%= form_with model: @book do |f| %>
        <div class="form-group">
          <%= f.label :title, 'Title' %>
          <%= f.text_field :title, class: 'form-control title' %>
        </div>
        <div class="form-group">
          <%= f.label :body, 'opinion' %>
          <%= f.text_area :body, class: 'form-control opinion' %>
        </div>
        <div class="form-group">
          <%= f.submit 'Update Book', class: 'btn btn-success'%>
        </div>
      <% end %>
      <%= link_to "Show", book_path(@book.id) %>
      |
      <%= link_to "Back", books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
  <%= render 'shaerd/error_explanation', valid: @book%>
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/info', user: @user%>
      <%= render 'new'%>
    </div>
    <div class="col-md-8 offset-md-1">
      <%= render 'books/books_list', books: @books %>
    </div>
  </div>
</div>

app/views/books/show.html.erb
  <div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/info', user: @book_user%>
      <%= render 'new' %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>
              <%= link_to user_path(@book.user) do %>
                <%= image_tag @book.user.get_profile_image(80,80) %>
                <br>
                <%= @book.user.name %>
              <% end %>
            </td>
            <td>
              <%= link_to @book.title, book_path(@book.id) %>
            </td>
            <td>
              <%= @book.body %>
            </td>
            <td>
              <% if @book.favorited_by?(current_user) %>
                <p>
                  <%= link_to book_favorites_path(@book), method: :delete do %>
                    <i class="fa-solid fa-heart text-danger">
                      <%= @book.favorites.count %>
                    </i>
                  <% end %>
                </p>
                <% else %>
                <p>
                  <%= link_to book_favorites_path(@book), method: :post do %>
                    <i class="fa-regular fa-heart">
                      <%= @book.favorites.count %>
                    </i>
                  <% end %>
                </p>
              <% end %>
            </td>
            <td>
              <p>コメント数：<%= @book.book_comments.count %></p>
            </td>
            <!--if文で、ユーザーかどうかの確認が必要-->
            <% if @book.user == current_user %>
              <td>
                <%= link_to edit_book_path(@book.id), class: 'btn btn-sm btn-success' do%>
                  Edit
                <% end %>
              </td>
              <td>
                <%= link_to book_path(@book.id), method: :delete, class: 'btn btn-sm btn-danger' do%>
                  Destroy
                <% end %>
              </td>
            <% end %>
          </tr>
        </tbody>
      </table>
      <div>
        <% @book.book_comments.each do |book_comment| %>
          <div class="row d-flex align-items-center">
            <div class="col-md-auto">
              <%= link_to user_path(book_comment.user) do %>
                <%= image_tag book_comment.user.get_profile_image(60,60) %>
                <br>
                <%= book_comment.user.name %>
              <% end %>
            </div>
            <div class="col-md-auto">
              <%= book_comment.comment %>
            </div>
            <div class="col-md-auto">
              <% if book_comment.user == current_user %>
                <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, class: 'btn btn-sm btn-danger' %>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
      <div>
        <%= form_with model: [@book, @book_comment] do |f| %>
          <div class="row">
            <%= f.text_area :comment, placeholder: "コメントをここに", class: "form-control", rows: "5" %>
          </div>
          <div class="row">
            <%= f.submit "送信" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/home/about.html.erb
<div class="container">
  <div class=row>
    <h1 class="px-3 mx-auto">welcome to <i class="fas fa-book"></i><strong>Bookers</strong> !!</h1>
  </div>
</div>

app/views/home/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong> !!</h1>
      <p>In <i class="fas fa-book"></i><strong>Bookers</strong>,</p>
      <p>you can share and exchange your opinions , inpressions , and emotions</p>
      <p>about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to "Log in", new_user_session_path, class: 'btn btn-info btn-sm btn-block mb-3 text-white' %>
        </div>
        <div class="row">
          <%= link_to "Sign up", new_user_registration_path, class: 'btn btn-success btn-sm btn-block mb-3 text-white' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong> !!</h1>
      <p>In <i class="fas fa-book"></i><strong>Bookers</strong>,</p>
      <p>you can share and exchange your opinions , inpressions , and emotions</p>
      <p>about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to new_user_session_path, class: 'btn btn-info btn-sm btn-block mb-3 text-white' do%>
            Log in
          <% end %>
        </div>
        <div class="row">
          <%= link_to new_user_registration_path, class: 'btn btn-success btn-sm btn-block mb-3 text-white' do%>
            Sign up
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <script src="https://kit.fontawesome.com/4604a8373b.js" crossorigin="anonymous"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand p-1" href="/">Bookers</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to user_path(current_user), class: 'nav-link text-white' do%>
                <i class="fas fa-home"></i>
                Home
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to users_path, class: 'nav-link text-white' do%>
                <i class="fas fa-users"></i>
                Users
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to books_path, class: 'nav-link text-white' do%>
                <i class="fas fa-book-open"></i>
                Books
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-white' do%>
                <i class="fas fa-sign-out-alt"></i>
                Log out
              <% end %>
            </li>
            <% else %>
            <li class="nav-item">
              <%= link_to root_path, class: 'nav-link text-white' do%>
                <i class="fas fa-home"></i>
                Home
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to about_path, class: 'nav-link text-white' do%>
                <i class="fas fa-link"></i>
                About
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_user_registration_path, class: 'nav-link text-white' do%>
                <i class="fas fa-user-plus"></i>
                Sign up
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_user_session_path, class: 'nav-link text-white' do%>
                <i class="fas fa-sign-in-alt"></i>
                Log in
              <% end %>
            </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <p><%= flash[:notice] %></p>
    <%= yield %>
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/shaerd/_error_explanation.html.erb
<div id="error_explanation">
  <% if valid.errors.any? %>
    <% if valid.errors.count == 1 %>
      <h3><%= valid.errors.count %> error prohibited this obj from being saved:</h3>
    <% else %>
      <h3><%= valid.errors.count %> errors prohibited this obj from being saved:</h3>
    <% end %>
    <ul>
      <% valid.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
</div>

app/views/users/_info.html.erb
<h2>User info</h2>
<%= image_tag user.get_profile_image(100,100) %>
<table class="table">
  <tbody>
    <tr>
      <th>name</th>
      <th><%= user.name %></th>
    </tr>
    <tr>
      <th>introduction</th>
      <th><%= user.introduction %></th>
    </tr>
  </tbody>
</table>
<div class="row">
  <%= link_to edit_user_path(user.id), class: "btn btn-outline-secondary btn-block" do%>
    <i class="fas fa-user-cog"></i>
  <% end %>
</div>

app/views/users/_users_list.html.erb
<h2>Users</h2>
<table class="table">
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td>
          <%= link_to user_path(user.id) do %>
            <%= image_tag user.get_profile_image(80,80) %>
          <% end %>
        </td>
        <td>
          <%= user.name%>
        </td>
        <td>
          <%= link_to "Show", user_path(user.id) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
      <%= render 'shaerd/error_explanation', valid: @user%>
      <%= form_with model: @user do |f| %>
        <div class="form-group">
          <%= f.label :name, 'Name' %>
          <%= f.text_field :name, class: 'form-control name' %>
        </div>
        <div class="form-group">
          <%= f.label :profile_image, 'Image' %>
          <%= f.file_field :profile_image, accept: "image/*", class: "w-100" %>
        </div>
        <div class="form-group">
          <%= f.label :introduction, 'Introduction' %>
          <%= f.text_area :introduction, class: 'form-control Introduction' %>
        </div>
        <div class="form-group">
          <%= f.submit 'Update User', class: 'btn btn-secondary'%>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'info', user: @user %>
      <%= render 'books/new' %>
    </div>
    <div class="col-md-8 offset-md-1">
      <%= render 'users_list', users: @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'info', user: @user %>
      <%= render 'books/new' %>
    </div>
    <div class="col-md-8 offset-md-1">
      <%= render 'books/books_list', books: @books %>
    </div>
  </div>
</div>